Update README.md
Lue-C/CapStone pull request #16
Opened 2022-05-22 10:21 UTC by haritha-1234

Read me file

2022-05-22 12:46 UTC, ChristianKlingler requested changes
I made some changes, feel free to review them :)

2022-05-22 14:02 UTC, haritha-1234 reviewed
looks good!

2022-05-22 14:02 UTC, haritha-1234 commented
It looks good!

2022-06-01 19:22 UTC, Lue-C approved these changes

2022-06-01 19:24 UTC, Lue-C approved these changes

2022-06-02 11:24 UTC, Lue-C approved these changes

2022-06-05 12:04 UTC, ChristianKlingler approved these changes

2022-06-05 12:05 UTC, merged